name: Ngrok RDP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download
      run: Invoke-WebRequest https://raw.githubusercontent.com/haxorbd02/Raw-Git/main/ngrok-stable-windows-amd64.zip

    - name: Extract
      run: Expand-Archive ngrok.zip

    - name: Auth
      run: C:\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

    - name: Enable Remote Desktop Firewall Rule
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Enable User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Connect to RDP
      run: |
        cd C:\ngrok
        sleep 10
        mstsc /v:$(C:\ngrok\ngrok.exe http 3389)/u:FutureBrightBD /p:P@S9rdO!
